const envFieldsNames = {
  postges: {
    HOST: 'POSTGRES_HOST',
    PORT: 'POSTGRES_PORT',
    USER: 'POSTGRES_USER',
    PASSWORD: 'POSTGRES_PASSWORD',
    DATABASE: 'POSTGRES_DB',
  },
  jwt: {
    ACCESS_TOKEN_SECRET: 'JWT_ACCESS_TOKEN_SECRET',
    REFRSH_TOKEN_SECRET: 'JWT_REFRESH_TOKEN_SECRET',
    ACCESS_TOKEN_EXPIRES_IN: 'JWT_ACCESS_TOKEN_EXPIRES_IN',
    REFRESH_TOKEN_EXPIRES_IN: 'JWT_REFRESH_TOKEN_EXPIRES_IN',
  },
  localAuth: {
    USERNAME_FIELD: 'LOCAL_AUTH_USERNAME_FIELD',
    PASSWORD_FIELD: 'LOCAL_AUTH_PASSWORD_FIELD',
  },
};

export default envFieldsNames;
